title: static-constructors
email: me@jacknoordhuis.net

lsi: false
safe: true
source: ./
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
