twitter_username: NxtLvlSoftware
github_username:  NxtLvlSoftware

lsi: false
safe: true
source: ./
incremental: false
theme: minima
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
