name: Stage dev changes

on:
  push:
    branches: [dev]

permissions:
  contents: write
  pull_request: write

env:
  GITHUB_ACTIONS: true

jobs:
  stage:
    name: Stage changes as pull request
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: staging
          title: Merge dev changes to staging
          assignees: JackNoordhuis
